import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Link from "next/link";
import { connectDB } from "@/util/database";
import AuthProvider from "@/util/SessionProvider";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hyunstagram",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = {}
  const sessioncookie = await getServerSession(authOptions)
  const db = (await connectDB).db('user')
  let user;
  if(sessioncookie){
    user = await db.collection('userinfo').findOne({email : sessioncookie.user.email})

  }else{
    user = null
  }
  session.user = user
  
  return (
    <html lang="en">
      <body className={inter.className}> 
        <AuthProvider>
        {children}
        </AuthProvider>
        
        {
          sessioncookie &&
          <div className="navbar" style={{ position: 'fixed', zIndex: 99, bottom: '0', background: '#000', width: '100%', maxWidth: '576px', display: 'flex', justifyContent: 'space-between', padding: '0 25px', alignItems: 'center', height: '50px' }}>
            <Link href="/" style={{ width: 'max-content' }}><img src="/img/homeclick.png" width={'24px'}></img></Link>
            <Link href="/usersearch" prefetch={true} style={{ width: 'max-content' }}><img src="https://hyunstagram.s3.ap-northeast-2.amazonaws.com/hyunstagram/search-white.png" width={'30px'}></img></Link>
            <Link href="/writewrap" prefetch={true} style={{ width: 'max-content' }}><img src="/img/upload.png" width={'24px'}></img></Link>
            <Link href="/reels" prefetch={true} style={{ width: 'max-content' }}><img src="/img/reels.png" width={'30px'}></img></Link>
            <Link href={"/profile/" + session.user.name} prefetch={true}>
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '2px', background: '#4d4d4d', borderRadius: '50%'}}>
              <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '1px', background: '#000', borderRadius: '50%' }}>
                <div style={{ borderRadius: '50%', width: 'auto', height: 'auto', overflow: 'hidden' }}>
                  <img src={'https://hyunstagram.s3.ap-northeast-2.amazonaws.com/hyunstagram/' + session.user.image} style={{ width: '25px', height: '25px' }} />
                </div>
              </div>
            </div>
            </Link>
          </div>
        }
      </body>
    </html>
  );
}
